// <auto-generated />
using ArenaLegendsRPG.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaLegendsRPG.Infrastructure.Migrations
{
    [DbContext(typeof(ArenaLegendsDbContext))]
    partial class ArenaLegendsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ArenaLegendsRPG.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAttackDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAttackResist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseMagicDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseMagicResist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ArenaLegendsRPG.Infrastructure.Entities.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ItemEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ArenaLegendsRPG.Infrastructure.Entities.ProtectionEntity", b =>
                {
                    b.HasBaseType("ArenaLegendsRPG.Infrastructure.Entities.ItemEntity");

                    b.Property<int>("AttackResist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicResist")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ProtectionEntity");
                });

            modelBuilder.Entity("ArenaLegendsRPG.Infrastructure.Entities.WeaponEntity", b =>
                {
                    b.HasBaseType("ArenaLegendsRPG.Infrastructure.Entities.ItemEntity");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicBonus")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("WeaponEntity");
                });

            modelBuilder.Entity("ArenaLegendsRPG.Infrastructure.Entities.ItemEntity", b =>
                {
                    b.HasOne("ArenaLegendsRPG.Infrastructure.Entities.CharacterEntity", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("ArenaLegendsRPG.Infrastructure.Entities.CharacterEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
